# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast"

# Site Settings
locale: "it-IT" # change to "en-US" when translated
title: "Hipácia"
title_separator: "-"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hipacia.pt" # the base hostname & protocol for your site, e.g. http://example.com
repository: "hipacia/hipacia.github.io"
name: "Hipácia" # NIPC 515260576
description: "Associação dos Investigadores Italianos em Portugal"

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-include-cache

# Reading Files
include: ["_pages"]

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
